[package]
name = "intcode_compiler"
version = "0.1.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "ic"

[dependencies]
structopt = "0.3.5"
